"""empty message

Revision ID: 0135d99a2936
Revises: 02b51a0e52f1
Create Date: 2026-02-04 23:43:28.764401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0135d99a2936'
down_revision = '02b51a0e52f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('favorites_locations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('locations_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locations_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'locations_id')
    )
    op.drop_table('Favorites')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    op.create_table('Favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='Favorites_character_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='Favorites_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='Favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Favorites_pkey')
    )
    op.drop_table('favorites_locations')
    op.drop_table('favorites_characters')
    # ### end Alembic commands ###
